apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.issuerSecret.name }}
  namespace: {{ .Values.issuerSecret.namespace }}
type: Opaque
data:
  token: {{ .Values.issuerSecret.data.token | b64enc }}